version: '3.5'

services:
  app:
    image: tranthaison1231/nest-enouvo-demo:latest
    build: 
      context: .
    container_name: nest-enouvo-demo
    restart: always
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
  
