name: CICD

on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} 
      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          tags: tranthaison1231/nest-enouvo-demo:latest
  deploy:
    needs: build
    runs-on: [ubuntu-latest]
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            docker stop nest-enouvo-demo || true
            docker rm nest-enouvo-demo || true
            docker pull tranthaison1231/nest-enouvo-demo:latest
            docker run -p 3000:3000 --env-file .env --name nest-enouvo-demo tranthaison1231/nest-enouvo-demo
      
