name: CICD

on:
  push:
    branches: [master]
jobs:
  lint:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Install dependencies
        run: yarn install
      - name: Lint
        run: yarn run lint

  build:
    runs-on: [ubuntu-latest]
    needs: lint
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} 
      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          push: true
          context: .
          tags: tranthaison1231/nest-enouvo-demo:latest
  deploy:
    needs: build
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Copy file name
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: ".env, docker-compose.yml"
          target: /home/ec2-user/nest-enouvo-demo

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            cd /home/ec2-user/nest-enouvo-demo
            rm -f .env
            touch .env
            echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
            docker-compose down
            docker-compose up -d
      
